import type { Metadata } from "next";
import { Layout, Menu } from "antd";
import { Content, Footer, Header } from "antd/es/layout/layout";
import React from "react";
import {AntdRegistry} from '@ant-design/nextjs-registry';
import "./index.css";
import Link from "next/link";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const items = [
	{ key: 0, label: <Link href={"/Home"}>Home</Link> },
	{ key: 1, label: <Link href={"/Posts"}>Posts</Link> },
	{ key: 2, label: <Link href={"/Albums"}>Albums</Link> },
	{ key: 3, label: <Link href={"/Todo"}>Todos</Link> },
];

const CusomLayout = ({children}:Readonly<{children: React.ReactNode}>) => {
		return (
		<html>
			<body>
				<AntdRegistry>
				<Layout className="layout">
			<Header className="header">
				<Menu
					theme="dark"
					mode="horizontal"
					defaultSelectedKeys={["0"]}
					items={items}
					style={{ flex: 1, minWidth: 0 }}
				/>
			</Header>
			<Content className="content">	{children}</Content>
			<Footer className="footer">Footer</Footer>
		</Layout>
		</AntdRegistry>
			</body>

		</html>
		
	);
};

export default CusomLayout;
